trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: preparation
  displayName: Preparation
  jobs:
  - job: getAssets
    displayName: Get Assets from Mainframe and GitHub
    steps:
steps:
    - task: CmdLine@2
      displayName: Download Mainframe Code
      inputs:
        script: |
          CD $(workspaceRoot)
          echo Downloading Mainframe Code using Parameters
          echo Host IP     : $(hostUri)
          echo Port        : $(hostPort)
          echo User ID     : $(hostUser)
          echo Codepage    : $(hostCodePage)
          echo ISPW Config : $(ispwConfig)
          echo Container   : $(ispwContainerName)
          echo Type        : $(ispwContainerType)
          echo Level       : $(ispwTargetLevel)
          
          $(cliPath)\SCMDownloaderCLI.bat ^
            -host $(hostUri) ^
            -port $(hostPort) ^
            -id $(hostUser) ^
            -pass $(hostPassword) ^
            -protocol None ^
            -code $(hostCodePage) ^
            -timeout 0 ^
            -targetFolder .\ ^
            -data $(topazCliWorkspace) ^
            -ispwServerConfig $(ispwConfig) ^
            -scm ispwc ^
            -ispwContainerName $(ispwContainerName) ^
            -ispwContainerType $(ispwContainerType) ^
            -ispwServerLevel $(ispwTargetLevel) ^
            -ispwDownloadAll true
