trigger: none

pool:
  name: 'Default'

# Set "runtime" variables
variables:
- group: 'mainframe-pipeline-parameters'
- name: 'gitRepo'
  value: 'FTSDEMO_$(ispwApplication)_Unit_Tests'
- name: 'ccSystem'
  value: 'AZURE_$(ispwContainerName)'
- name: 'ccDdio'
  value: 'SALESSUP.$(ispwApplication).$(ispwLevel).LOAD.SSD'
- name: 'sonarProjectName'
  value: 'RNU_$(ispwApplication)_Azure'
- name: 'sonarSources'
  value: '.\$(ispwApplication)\MF_Source'
- name: 'tttEnvironment'
  value: '5b508b8a787be73b59238d38'
- name: 'testFolderVt'
  value: 'tests/Virtualized_Tests'
- name: 'testResultFolderVt'
  value: './TTTSonar/Virtualized_Tests.cli.suite.sonar.xml'
- name: 'codeCoverageReportFile'
  value: 'Coverage/CodeCoverage.xml'
- name: topazCliWorkspace
  value: '.\TopazCliWkspc'
- name: ispwTargetLevel
  ${{ if eq(variables['ispwLevel'], 'DEV1') }}:
    value: QA1
  ${{ elseif eq(variables['ispwLevel'], 'DEV2') }}:
    value: QA2
  ${{ else}}:
    value: QA3
- name: contextVars
  value: '"ispw_app=$(ispwApplication),ispw_level=$(ispwTargetLevel)"'

stages:
- stage: preparation
  displayName: Preparation
  jobs:
  - job: getAssets
    displayName: Get Assets from Mainframe and GitHub
    steps:

  # Clear Workspace
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Remove-Item $(workspaceRoot)\* -Recurse -Force
  
  # Download Mainframe Sources from ISPW Container
    # The command line execution is equivalent to the following Jenkins Groovy method call
    # checkout(
    #   [
    #     $class:             'IspwContainerConfiguration', 
    #     connectionId:       "${pipelineParams.hciConnectionId}",
    #     credentialsId:      "${pipelineParams.hciToken}", 
    #     componentType:      '', 
    #     containerName:      pipelineParams.ispwAssignment, 
    #     containerType:      '0', // 0 Assignment, 1 Release, 2 Set, 
    #     ispwDownloadAll:    false, 
    #     ispwDownloadIncl:   true, 
    #     serverConfig:       '', 
    #     serverLevel:        ispwTargetLevel
    #   ]
    - task: CmdLine@2
      displayName: Download Mainframe Code
      inputs:
        script: |
          CD $(workspaceRoot)
          echo Downloading Mainframe Code using Parameters
          echo Host IP     : $(hostUri)
          echo Port        : $(hostPort)
          echo User ID     : $(hostUser)
          echo Codepage    : $(hostCodePage)
          echo ISPW Config : $(ispwConfig)
          echo Container   : $(ispwContainerName)
          echo Type        : $(ispwContainerType)
          echo Level       : $(ispwTargetLevel)
          
          $(cliPath)\SCMDownloaderCLI.bat ^
            -host $(hostUri) ^
            -port $(hostPort) ^
            -id $(hostUser) ^
            -pass $(hostPassword) ^
            -protocol None ^
            -code $(hostCodePage) ^
            -timeout 0 ^
            -targetFolder .\ ^
            -data $(topazCliWorkspace) ^
            -ispwServerConfig $(ispwConfig) ^
            -scm ispwc ^
            -ispwContainerName $(ispwContainerName) ^
            -ispwContainerType $(ispwContainerType) ^
            -ispwServerLevel $(ispwTargetLevel) ^
            -ispwDownloadAll true




