trigger: 
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Download Source from ISPW Container
  displayName: Download
  jobs:
  - job: getAssets
    displayName: Get Assets from Mainframe and GitHub
    steps:

  # Clear Workspace
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Remove-Item $(workspaceRoot)\* -Recurse -Force
  
  # Download Mainframe Sources from ISPW Container
    # The command line execution is equivalent to the following Jenkins Groovy method call
    # checkout(
    #   [
    #     $class:             'IspwContainerConfiguration', 
    #     connectionId:       "${pipelineParams.hciConnectionId}",
    #     credentialsId:      "${pipelineParams.hciToken}", 
    #     componentType:      '', 
    #     containerName:      pipelineParams.ispwAssignment, 
    #     containerType:      '0', // 0 Assignment, 1 Release, 2 Set, 
    #     ispwDownloadAll:    false, 
    #     ispwDownloadIncl:   true, 
    #     serverConfig:       '', 
    #     serverLevel:        ispwTargetLevel
    #   ]
    - task: CmdLine@2
      displayName: Download Mainframe Code
      inputs:
        script: |
          CD $(workspaceRoot)
          echo Downloading Mainframe Code using Parameters
          echo Host IP     : $(hostUri)
          echo Port        : $(hostPort)
          echo User ID     : $(hostUser)
          echo Codepage    : $(hostCodePage)
          echo ISPW Config : $(ispwConfig)
          echo Container   : $(ispwContainerName)
          echo Type        : $(ispwContainerType)
          echo Level       : $(ispwTargetLevel)
          
          $(cliPath)\SCMDownloaderCLI.bat ^
            -host $(hostUri) ^
            -port $(hostPort) ^
            -id $(hostUser) ^
            -pass $(hostPassword) ^
            -protocol None ^
            -code $(hostCodePage) ^
            -timeout 0 ^
            -targetFolder .\ ^
            -data $(topazCliWorkspace) ^
            -ispwServerConfig $(ispwConfig) ^
            -scm ispwc ^
            -ispwContainerName $(ispwContainerName) ^
            -ispwContainerType $(ispwContainerType) ^
            -ispwServerLevel $(ispwTargetLevel) ^
            -ispwDownloadAll true




